seproject/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class User(db.Model, UserMixin):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key = True)
    fname = db.Column(db.String(30), nullable = False)
    lname = db.Column(db.String(30), nullable = False)
    email = db.Column(db.String(30), unique=True, nullable = False)
    username = db.Column(db.String(30), unique=True, nullable = False)
    password = db.Column(db.String(300), nullable=False)
    subjects = db.Column(db.String(30), nullable = True)
    role = db.Column(db.String(30), nullable = False)
    linkedin = db.Column(db.String, nullable = True)


seproject/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager, login_manager
from flask_restful import Api


db = SQLAlchemy()
DB_NAME = "myData.db"
# DB_NAME = "project.sqlite3"
def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'param'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)
    api = Api(app)
    from .api import UserAPI
    api.add_resource(UserAPI, '/api/user', '/api/user/<string:username>')
    from .views import views
    app.register_blueprint(views, url_prefix="/")
    from .models import User
    create_db(app)
    login_manager = LoginManager()
    login_manager.login_view = "views.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))


    return  app, api

def create_db(app):
    if not path.exists("seproject/"+ DB_NAME):
        db.create_all(app=app)
    print('DATABASE ALREADY EXISTS')

seproject/views.py
from re import S
from flask import Blueprint, render_template, request, flash
from flask_login import login_user, logout_user, current_user
from flask_login.utils import login_required
from werkzeug.utils import redirect
from .models import User
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
import requests
from datetime import datetime

views = Blueprint("views", __name__)

BASE = 'http://127.0.0.1:5000'

@views.route('/dashboard', methods = ['GET', 'POST'])
@login_required
def home():
    if current_user.role == "Mentee":
        mentorlist = User.query.filter_by(role="Mentor").all()
        return render_template('dashboard.html' , name=current_user.username, mentorlist=mentorlist )
    else:
        menteelist = User.query.filter_by(role="Mentee").all()
        return render_template('dashboard_mentee.html' , name=current_user.username, menteelist=menteelist )

@views.route('/', methods=['GET'])
def landing():
    return render_template('landing.html')


@views.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get("username")
        password = request.form.get("password")

        user = User.query.filter_by(username=username).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect('/dashboard')
            else:
                flash('Password is incorrect.', category='error')
        else:
            flash('Username does not exist.', category='error')

    return render_template('login.html')




@views.route('/register', methods = ['GET', 'POST'])
def register():
    return render_template('register.html')


@views.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect('/')

seproject/templates/dashboard.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{{ name }}'s Dashboard</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://unpkg.com/tailwindcss@^3.0/dist/tailwind.min.css" rel="stylesheet">

  <script src="https://cdn.tailwindcss.com"></script>



  <style>
    .student {
      flex: 20%;
      padding: 10px;
      margin: 5px;
      background-color: #f3f3f3;
      inline-size: 100%;
      border-radius: 15px;

    }
  </style>
</head>

<body>
  <div class="isolate bg-white">
    <div class="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]">
      <svg
        class="relative left-[calc(50%-11rem)] -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] sm:left-[calc(50%-30rem)] sm:h-[42.375rem]"
        viewBox="0 0 1155 678" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path fill="url(#45de2b6b-92d5-4d68-a6a0-9b9b2abad533)" fill-opacity=".3"
          d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z" />
        <defs>
          <linearGradient id="45de2b6b-92d5-4d68-a6a0-9b9b2abad533" x1="1155.49" x2="-78.208" y1=".177" y2="474.645"
            gradientUnits="userSpaceOnUse">
            <stop stop-color="#9089FC"></stop>
            <stop offset="1" stop-color="#FF80B5"></stop>
          </linearGradient>
        </defs>
      </svg>
    </div>
    <div class="px-6 pt-6 lg:px-8">
      <div>
        <nav class="flex h-9 items-center justify-between" aria-label="Global">
          <div class="flex lg:min-w-0 lg:flex-1" aria-label="Global">
            <a href="#" class="-m-1.5 p-1.5">
              <span class="sr-only">Mentorship</span>
              <img class="h-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
            </a>
          </div>
          <div class="flex lg:hidden">
            <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
              <span class="sr-only">Open main menu</span>
              <!-- Heroicon name: outline/bars-3 -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
              </svg>
            </button>
          </div>
          <div class="hidden lg:flex lg:min-w-0 lg:flex-1 lg:justify-center lg:gap-x-12">
            <a href="#" class="font-semibold text-gray-900 hover:text-gray-900">About Us</a>
          </div>
          <div class="hidden lg:flex lg:min-w-0 lg:flex-1 lg:justify-end">
            <a href="{{ url_for('views.logout') }}"
              class="inline-block rounded-lg px-3 py-1.5 text-sm font-semibold leading-6 text-gray-900 shadow-sm ring-1 ring-gray-900/10 hover:ring-gray-900/20">Log
              out</a>
          </div>
        </nav>
        <!-- Mobile menu, show/hide based on menu open state. -->
        <div role="dialog" aria-modal="true">
          <div focus="true" class="fixed inset-0 z-10 overflow-y-auto bg-white px-6 py-6 lg:hidden">
            <div class="flex h-9 items-center justify-between">
              <div class="flex">
                <a href="#" class="-m-1.5 p-1.5">
                  <span class="sr-only">Your Company</span>
                  <img class="h-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
                </a>
              </div>
              <div class="flex">
                <button type="button"
                  class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
                  <span class="sr-only">Close menu</span>
                  <!-- Heroicon name: outline/x-mark -->
                  <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                    stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>
            <div class="mt-6 flow-root">
              <div class="-my-6 divide-y divide-gray-500/10">

                <div class="py-6">
                  <a href="{{ url_for('views.logout') }}"
                    class="-mx-3 block rounded-lg py-2.5 px-3 text-base font-semibold leading-6 text-gray-900 hover:bg-gray-400/10">Log
                    out</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <main>
      <div class="relative px-6 lg:px-8">
        <div class="mx-auto max-w-3xl pt-20 pb-32 sm:pt-20 sm:pb-40">
          <div>
            <div>
              <h1 class="text-4xl font-bold tracking-tight sm:text-center sm:text-6xl">
                Find Your Mentors Here
              </h1>
              <br>
              <h3 class="text-4xl font-bold tracking-tight sm:text-center sm:text-3xl italic">
                Your Username : {{ name }}
              </h3>
              <br>
              <p class="sm:text-center w-full px-3 text-gray-600 text-xl italic">
                Please find the list of our mentors below. Feel free to contact the mentors based on your subject
                interest & the Mentor's expertise.
              </p>
              <p class="sm:text-center w-full px-3 text-gray-600 text-xl italic">
                Remember to be respectful while comunicating!
              </p>
              <br>
              <h3 class="text-4xl font-bold tracking-tight sm:text-center sm:text-3xl italic">
                Please Generate a Google Meet Link by clicking below!
              </h3>
              <div align="center"><br>
               <a href="https://meet.google.com"><button
                class=" bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded">
                Click Here! 
              </button></a><br><br></div>
              
              <h5 class=" tracking-wide  sm:text-center ">
                {% for m in mentorlist %}
                <div class="student ">
                  <p><b>Mentee Name:</b> {{ m.fname }} {{ m.lname }}</p>
                  <p><b>Mentor's Area of Expertise:</b> {{ m.subjects }}</p>
                  <p><b>Mentee Email ID:</b> <a href="mailto:{{ m.email }}"><u>{{ m.email }}</u></a></p>
                  <p><b>Mentee LinkedIn:</b> <a href="https://{{ m.linkedin }}"><u>Click Here!</u></a></p>
                </div>
                {% endfor %}
              </h5>
            </div>
            <div
              class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]">
              <svg
                class="relative left-[calc(50%+3rem)] h-[21.1875rem] max-w-none -translate-x-1/2 sm:left-[calc(50%+36rem)] sm:h-[42.375rem]"
                viewBox="0 0 1155 678" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill="url(#ecb5b0c9-546c-4772-8c71-4d3f06d544bc)" fill-opacity=".3"
                  d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z" />
                <defs>
                  <linearGradient id="ecb5b0c9-546c-4772-8c71-4d3f06d544bc" x1="1155.49" x2="-78.208" y1=".177"
                    y2="474.645" gradientUnits="userSpaceOnUse">
                    <stop stop-color="#9089FC"></stop>
                    <stop offset="1" stop-color="#FF80B5"></stop>
                  </linearGradient>
                </defs>
              </svg>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</body>

</html>

seproject/templates/dashboard_mentee.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{{ name }}'s Dashboard</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet"> -->

  <script src="https://cdn.tailwindcss.com"></script>



  <style>
    .student {
      flex: 20%;
      padding: 10px;
      margin: 5px;
      background-color: #f3f3f3;
      inline-size: 100%;
      border-radius: 15px;
    }
  </style>
</head>

<body>
  <div class="isolate bg-white">
    <div class="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]">
      <svg
        class="relative left-[calc(50%-11rem)] -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] sm:left-[calc(50%-30rem)] sm:h-[42.375rem]"
        viewBox="0 0 1155 678" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path fill="url(#45de2b6b-92d5-4d68-a6a0-9b9b2abad533)" fill-opacity=".3"
          d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z" />
        <defs>
          <linearGradient id="45de2b6b-92d5-4d68-a6a0-9b9b2abad533" x1="1155.49" x2="-78.208" y1=".177" y2="474.645"
            gradientUnits="userSpaceOnUse">
            <stop stop-color="#9089FC"></stop>
            <stop offset="1" stop-color="#FF80B5"></stop>
          </linearGradient>
        </defs>
      </svg>
    </div>
    <div class="px-6 pt-6 lg:px-8">
      <div>
        <nav class="flex h-9 items-center justify-between" aria-label="Global">
          <div class="flex lg:min-w-0 lg:flex-1" aria-label="Global">
            <a href="#" class="-m-1.5 p-1.5">
              <span class="sr-only">Mentorship</span>
              <img class="h-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
            </a>
          </div>
          <div class="flex lg:hidden">
            <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
              <span class="sr-only">Open main menu</span>
              <!-- Heroicon name: outline/bars-3 -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
              </svg>
            </button>
          </div>
          <div class="hidden lg:flex lg:min-w-0 lg:flex-1 lg:justify-center lg:gap-x-12">
            <a href="#" class="font-semibold text-gray-900 hover:text-gray-900">About Us</a>
          </div>
          <div class="hidden lg:flex lg:min-w-0 lg:flex-1 lg:justify-end">
            <a href="{{ url_for('views.logout') }}"
              class="inline-block rounded-lg px-3 py-1.5 text-sm font-semibold leading-6 text-gray-900 shadow-sm ring-1 ring-gray-900/10 hover:ring-gray-900/20">Log
              out</a>
          </div>
        </nav>
        <!-- Mobile menu, show/hide based on menu open state. -->
        <div role="dialog" aria-modal="true">
          <div focus="true" class="fixed inset-0 z-10 overflow-y-auto bg-white px-6 py-6 lg:hidden">
            <div class="flex h-9 items-center justify-between">
              <div class="flex">
                <a href="#" class="-m-1.5 p-1.5">
                  <span class="sr-only">Your Company</span>
                  <img class="h-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
                </a>
              </div>
              <div class="flex">
                <button type="button"
                  class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
                  <span class="sr-only">Close menu</span>
                  <!-- Heroicon name: outline/x-mark -->
                  <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                    stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>
            <div class="mt-6 flow-root">
              <div class="-my-6 divide-y divide-gray-500/10">
                <div class="space-y-2 py-6">
                  <a href="#"
                    class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10">
                    About Us</a>

                </div>
                <div class="py-6">
                  <a href="{{ url_for('views.logout') }}"
                    class="-mx-3 block rounded-lg py-2.5 px-3 text-base font-semibold leading-6 text-gray-900 hover:bg-gray-400/10">Log
                    out</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <main>
      <div class="relative px-6 lg:px-8">
        <div class="mx-auto max-w-3xl  pb-32 sm:pt-20 sm:pb-40">
          <div>
            <div>
              <h1 class="text-4xl font-bold tracking-tight sm:text-center sm:text-6xl">
                Find Your Mentees Here!
              </h1>

              <h3 class="text-4xl font-bold tracking-tight sm:text-center sm:text-3xl">
                Your Username : {{ name }}
              </h3><br>
              <!-- <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                   <input name="fname"
                      class="appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"
                      id="grid-first-name" type="text" placeholder="search...">
                </div>
                <div class="w-full md:w-1/2 px-3">
                  <button type="submit"
                  class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded">
                  >
               </button>
                </div> -->
             </div>
              <h5 class=" tracking-tight sm:text-center">

                {% for m in menteelist %}
                <div class="student">

                  <b>
                    <p>Mentor Name: {{ m.fname }} {{ m.lname }}</p>
                    <p>Mentor Email ID: <a href="mailto:{{ m.email }}" >{{ m.email }}</a></p>
                    <p>Mentor LinkedIn: <a href="https://{{ m.linkedin }}" >Click Here!</a></p>
                    <!-- <p>Mentor's Area of Expertise: {{ m.subjects }}</p> -->
                  </b>
                </div>
                {% endfor %}
              </h5>
            </div>
            <div
              class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]">
              <svg
                class="relative left-[calc(50%+3rem)] h-[21.1875rem] max-w-none -translate-x-1/2 sm:left-[calc(50%+36rem)] sm:h-[42.375rem]"
                viewBox="0 0 1155 678" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill="url(#ecb5b0c9-546c-4772-8c71-4d3f06d544bc)" fill-opacity=".3"
                  d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z" />
                <defs>
                  <linearGradient id="ecb5b0c9-546c-4772-8c71-4d3f06d544bc" x1="1155.49" x2="-78.208" y1=".177"
                    y2="474.645" gradientUnits="userSpaceOnUse">
                    <stop stop-color="#9089FC"></stop>
                    <stop offset="1" stop-color="#FF80B5"></stop>
                  </linearGradient>
                </defs>
              </svg>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</body>

</html>

seproject/templates/review.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/review.css') }}">
    </head>
    <body>
        <header class="p-3  text-white">
            <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                FLASH CARDS
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{{ url_for('views.home') }}" class="nav-link px-2 text-secondary">Home</a></li>
                
                </ul>
                <div class="text-end">
                <a href="{{ url_for('views.logout') }}" class="btn btn-outline-dark btn-warning me-2">Logout</a>
                
                </div>
            </div>
            </div>
        </header>

<br><br>
    <center>
        <!-- Button trigger modal -->
        <button style="margin-bottom: 50px;"type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#exampleModal">
          + Add Cards
        </button>
        <br>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">ADD CARD!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form class="row g-3" action="/api/{{ deck }}" method="POST">
                              <div class="col-auto">
                                <label for="front" class="visually-hidden">Front</label>
                                <input type="text" class="form-control" id="front" placeholder="front..." name="front">
                                <br>
                                <label for="back" class="visually-hidden">Back</label>
                                <input type="text" class="form-control" id="back" placeholder="back..." name="back">
                              </div>
                              <div class="col-auto">

                                <br>
                                <br>
                                <button type="submit" class="btn btn-primary mb-3">Add</button>
                                
                              </div>
                            </form>
              </div>
              <div class="modal-footer">
                
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                
              </div>
            </div>
          </div>
        </div>
    </center>

        <center>
            <div class="big">
              
            <!--div class="cardcontainer">
                <div class="card">
                  
                    <div class="front"> Front: {% if data %} No Cards Yet {% else %} {{front}} {% endif %}</div>
                    
                    <div  class="back"> Back: {% if data %} Click Add Cards to get started {% else %} {{back}} {% endif %}</div>
                </div> 
            </div-->
            
            <div class="flip-card">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <div class="front"> <p>Front:</p> {% if data %} No Cards Yet {% else %} {{front}} {% endif %}</div>
                </div>
                <div class="flip-card-back">
                  <div  class="back"> <p>Back:</p> {% if data %} Click Add Cards to get started {% else %} {{back}} {% endif %}</div>
                </div>
              </div>
            </div>
 

            <form id="autoform" action="/review/{{ deck }}/{{ card_id }}" method="POST" name="autoform">    
                <div class="rating">
                  <br>
                  <p class="rate">Please rate below depending on how easy or difficult was it for you to answer the displayed question and the card will automatically be shuffled!</p>
                    <input onclick="document.getElementById('autoform').submit();" type="radio" name="score" id="rata4" value="10" {% if data %} disabled {% endif %}><label for="rata4">Easy</label><br>
                    <input onclick="document.getElementById('autoform').submit();" type="radio" name="score" id="rata3" value="8" {% if data %} disabled {% endif %}><label for="rata3">Average</label><br>
                    <input onclick="document.getElementById('autoform').submit();" type="radio" name="score" id="rata2" value="6" {% if data %} disabled {% endif %}><label for="rata2">Hard</label>
                    

                </div>
            </form>

            </div>   
        </center>


        
        
    </body>
</html>